on: [push]

jobs:
  codepen_sync_job:
    runs-on: ubuntu-latest
    name: Sync the Hungry Shark pen on Codepen to this repo
    steps:
    - name: Codepen Sync Action
      id: codepen-sync-action
      uses: mpopv/codepen-sync-action@1.0.0
      with:
        codepen-id: 'dyPddMW'
    - name: Get the output time
      run: echo "The time was ${{ steps.codepen-sync-action.outputs.time }}"